// <auto-generated />
namespace DAL.UCMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TT2713SpsModified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TT2713SpsModified));
        
        string IMigrationMetadata.Id
        {
            get { return "201712040134114_TT-271-3SpsModified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
