// <auto-generated />
namespace DAL.UCMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class change_menu_label_for_help_centre1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_menu_label_for_help_centre1));
        
        string IMigrationMetadata.Id
        {
            get { return "201803080401059_change_menu_label_for_help_centre1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
