// <auto-generated />
namespace DAL.UCMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_GET_IMPLEMENT_IMAGE_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_GET_IMPLEMENT_IMAGE_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201805180235218_Added_GET_IMPLEMENT_IMAGE_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
