// <auto-generated />
namespace DAL.UCMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TableFixMobileUploadImageTemporary2UC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TableFixMobileUploadImageTemporary2UC));
        
        string IMigrationMetadata.Id
        {
            get { return "201806182304358_TableFixMobileUploadImageTemporary2UC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
