// <auto-generated />
namespace DAL.UCMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_decimal_option_for_track_inspection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_decimal_option_for_track_inspection));
        
        string IMigrationMetadata.Id
        {
            get { return "201803042341046_add_decimal_option_for_track_inspection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
