// <auto-generated />
namespace DAL.UCMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Table__Track_InspectionForMiningShovels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Table__Track_InspectionForMiningShovels));
        
        string IMigrationMetadata.Id
        {
            get { return "201806040615591_Table__Track_InspectionForMiningShovels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
