// <auto-generated />
namespace DAL.UCMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class return_track_interpretation_4T_UP_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(return_track_interpretation_4T_UP_2));
        
        string IMigrationMetadata.Id
        {
            get { return "201806150147128_return_track_interpretation_4T_UP_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
