// <auto-generated />
namespace DAL.UCMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TableForLinksConditionUC2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TableForLinksConditionUC2));
        
        string IMigrationMetadata.Id
        {
            get { return "201804060231562_TableForLinksConditionUC2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
