// <auto-generated />
namespace DAL.UCMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingNameToDealershipBranding : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingNameToDealershipBranding));
        
        string IMigrationMetadata.Id
        {
            get { return "201801152314331_AddingNameToDealershipBranding"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
