// <auto-generated />
namespace DAL.UCMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TableFixMobileUploadImageTemporaryUC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TableFixMobileUploadImageTemporaryUC));
        
        string IMigrationMetadata.Id
        {
            get { return "201806182258437_TableFixMobileUploadImageTemporaryUC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
