// <auto-generated />
namespace DAL.UCMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixInspectionSearch : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixInspectionSearch));
        
        string IMigrationMetadata.Id
        {
            get { return "201807250020442_FixInspectionSearch"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
