// <auto-generated />
namespace DAL.UCMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TT415ExtraColumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TT415ExtraColumns));
        
        string IMigrationMetadata.Id
        {
            get { return "201804120401594_TT415ExtraColumns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
