// <auto-generated />
namespace DAL.UCMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class return_compart_model_list_4T1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(return_compart_model_list_4T1));
        
        string IMigrationMetadata.Id
        {
            get { return "201802072229321_return_compart_model_list_4T1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
