// <auto-generated />
namespace DAL.UCMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class return_track_inspection_report_details : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(return_track_inspection_report_details));
        
        string IMigrationMetadata.Id
        {
            get { return "201801100323423_return_track_inspection_report_details"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
