// <auto-generated />
namespace DAL.SHAREDCONTEXTMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class set_event_comments_to_nvarchar2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(set_event_comments_to_nvarchar2));
        
        string IMigrationMetadata.Id
        {
            get { return "201802090007361_set_event_comments_to_nvarchar2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
