// <auto-generated />
namespace DAL.SHAREDCONTEXTMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MSP_Database_structure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MSP_Database_structure));
        
        string IMigrationMetadata.Id
        {
            get { return "201803150037439_MSP_Database_structure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
