// <auto-generated />
namespace DAL.SHAREDCONTEXTMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CompartMeasurePointIdAddedToTheCompartExt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CompartMeasurePointIdAddedToTheCompartExt));
        
        string IMigrationMetadata.Id
        {
            get { return "201806220436039_CompartMeasurePointIdAddedToTheCompartExt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
