// <auto-generated />
namespace DAL.SHAREDCONTEXTMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddShoeSizeList : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddShoeSizeList));
        
        string IMigrationMetadata.Id
        {
            get { return "201804060300208_AddShoeSizeList"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
