// <auto-generated />
namespace DAL.SHAREDCONTEXTMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewColumns_ShoeCount_TrackInspectionTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewColumns_ShoeCount_TrackInspectionTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201808280616000_NewColumns_ShoeCount_TrackInspectionTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
