// <auto-generated />
namespace DAL.GETMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class rollback_return_GET_IMPLEMENT_COMPARTTYPE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rollback_return_GET_IMPLEMENT_COMPARTTYPE));
        
        string IMigrationMetadata.Id
        {
            get { return "201711230236022_rollback_return_GET_IMPLEMENT_COMPARTTYPE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
