// <auto-generated />
namespace DAL.GETMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_GETEnabled_key : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_GETEnabled_key));
        
        string IMigrationMetadata.Id
        {
            get { return "201711302305049_add_GETEnabled_key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
