// <auto-generated />
namespace DAL.GETMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_GET_EVENT_types : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_GET_EVENT_types));
        
        string IMigrationMetadata.Id
        {
            get { return "201801230516007_add_GET_EVENT_types"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
