// <auto-generated />
namespace DAL.GETMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class insert_GET_INVENTORY_status_types : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(insert_GET_INVENTORY_status_types));
        
        string IMigrationMetadata.Id
        {
            get { return "201801040359221_insert_GET_INVENTORY_status_types"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
