// <auto-generated />
namespace DAL.GETMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class insert_GET_INVENTORY_status_types1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(insert_GET_INVENTORY_status_types1));
        
        string IMigrationMetadata.Id
        {
            get { return "201801090416042_insert_GET_INVENTORY_status_types1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
