// <auto-generated />
namespace DAL.GETMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ImportGET_IMPLEMENT_COMPARTTYPETable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImportGET_IMPLEMENT_COMPARTTYPETable));
        
        string IMigrationMetadata.Id
        {
            get { return "201801222322204_ImportGET_IMPLEMENT_COMPARTTYPETable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
