// <auto-generated />
namespace DAL.GETMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_workshop_to_inventory_table1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_workshop_to_inventory_table1));
        
        string IMigrationMetadata.Id
        {
            get { return "201802010219582_add_workshop_to_inventory_table1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
