// <auto-generated />
namespace DAL.GETMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changes_08_05_2018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changes_08_05_2018));
        
        string IMigrationMetadata.Id
        {
            get { return "201805072354157_changes_08_05_2018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
