// <auto-generated />
namespace DAL.GETMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fixDALonDevTest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixDALonDevTest));
        
        string IMigrationMetadata.Id
        {
            get { return "201809180655511_fixDALonDevTest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
