// <auto-generated />
namespace DAL.GETMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class set_event_comments_to_nvarchar1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(set_event_comments_to_nvarchar1));
        
        string IMigrationMetadata.Id
        {
            get { return "201802082322381_set_event_comments_to_nvarchar1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
