// <auto-generated />
namespace DAL.GETMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DropConstraint_IX_LU_COMPART_TYPE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropConstraint_IX_LU_COMPART_TYPE));
        
        string IMigrationMetadata.Id
        {
            get { return "201805090444235_DropConstraint_IX_LU_COMPART_TYPE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
