// <auto-generated />
namespace DAL.GETMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_new_GET_actions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_new_GET_actions));
        
        string IMigrationMetadata.Id
        {
            get { return "201802020601325_add_new_GET_actions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
